CREATE TABLE "USER_INFO" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"USER_PW"	VARCHAR2(255)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(50)		NOT NULL,
	"USER_TEL"	CHAR(11)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"USER_BIRTH"	DATE		NOT NULL,
	"USER_GENDER"	CHAR(1)		NOT NULL,
	"USER_ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_AMOUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"USER_ROLE"	CHAR(1)	DEFAULT 'C'	NOT NULL,
	"USER_RATING"	NUMBER	DEFAULT 1	NOT NULL,
	"USER_CLOSE"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "USER_INFO"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "USER_INFO"."USER_ID" IS '회원 아이디';

COMMENT ON COLUMN "USER_INFO"."USER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "USER_INFO"."USER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "USER_INFO"."USER_TEL" IS '회원 전화번호, "-"빼고 10~11자';

COMMENT ON COLUMN "USER_INFO"."USER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "USER_INFO"."USER_BIRTH" IS '회원 생년월일 8자리 YYYY-MM-DD';

COMMENT ON COLUMN "USER_INFO"."USER_GENDER" IS 'M:MALE(남), F:FEMALE(여)';

COMMENT ON COLUMN "USER_INFO"."USER_ENROLL_DT" IS '회원가입일자';

COMMENT ON COLUMN "USER_INFO"."USER_AMOUNT" IS '누적사용금액 -> 사용금액을 통한 등급책정, 등급을 클래스를 통해서 설정';

COMMENT ON COLUMN "USER_INFO"."USER_ROLE" IS 'A: ADMIN    C:CUSTOMER';

COMMENT ON COLUMN "USER_INFO"."USER_RATING" IS '1: 브론즈 2: 실버 3: 골드 4: 플래티넘';

COMMENT ON COLUMN "USER_INFO"."USER_CLOSE" IS 'Y: 탈퇴 , N : 활성화';

CREATE TABLE "SALES" (
	"YEAR_QUATER"	CHAR(5)		NOT NULL,
	"REVENUE_TICKET"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SALES"."YEAR_QUATER" IS '분기';

COMMENT ON COLUMN "SALES"."REVENUE_TICKET" IS '티켓매출';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(300)		NULL,
	"NOTICE_CONTENT"	VARCHAR2(3000)		NULL,
	"NOTICE_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_VIEWPOINT"	NUMBER	DEFAULT 0	NOT NULL,
	"NOTICE_FL"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항번호(SEQ_NOTICE_NO)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지사항제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지사항내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_ENROLL_DATE" IS '공지사항날짜';

COMMENT ON COLUMN "NOTICE"."NOTICE_VIEWPOINT" IS '조회수';

COMMENT ON COLUMN "NOTICE"."NOTICE_FL" IS '처리여부';

CREATE TABLE "QNA" (
	"QNA_NO"	NUMBER		NOT NULL,
	"QNA_TITLE"	VARCHAR2(300)		NOT NULL,
	"QNA_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"QNA_ENROLL_DATE"	DATE		NOT NULL,
	"QNA_DELETE_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"QNA_CHECK_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"QNA_CATEGORY"	CHAR(1)		NOT NULL,
	"USER_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QNA"."QNA_NO" IS '문의번호(SEQ_QNA_NO)';

COMMENT ON COLUMN "QNA"."QNA_TITLE" IS '문의제목';

COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '문의내용';

COMMENT ON COLUMN "QNA"."QNA_ENROLL_DATE" IS '문의날짜';

COMMENT ON COLUMN "QNA"."QNA_DELETE_FL" IS '삭제여부(N:삭제X, Y:삭제O)';

COMMENT ON COLUMN "QNA"."QNA_CHECK_FL" IS '처리여부(N: 처리X, Y: 처리O)';

COMMENT ON COLUMN "QNA"."QNA_CATEGORY" IS '문의 분류(P:영화관, M:영화, U:멤버쉽, B:예매/결제, H:홈페이지 A:계정)';

COMMENT ON COLUMN "QNA"."USER_NO2" IS '회원 번호(SEQ_USER_NO)';

CREATE TABLE "MOVIE_SCHEDULE" (
	"MOVIE_TIME"	DATE		NOT NULL,
	"MOVIE_THEATER"	CHAR(1)		NOT NULL,
	"MOVIE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE_SCHEDULE"."MOVIE_TIME" IS '상영날짜 및 시간';

COMMENT ON COLUMN "MOVIE_SCHEDULE"."MOVIE_THEATER" IS '상영관번호';

COMMENT ON COLUMN "MOVIE_SCHEDULE"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

CREATE TABLE "SEAT" (
	"SEAT_NO"	VARCHAR2(10)		NOT NULL,
	"MOVIE_THEATER"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "SEAT"."SEAT_NO" IS '좌석번호';

COMMENT ON COLUMN "SEAT"."MOVIE_THEATER" IS '상영관번호';

CREATE TABLE "MOVIE" (
	"MOVIE_NO"	NUMBER		NOT NULL,
	"MOVIE_TITLE"	VARCHAR2(100)		NOT NULL,
	"POSTER"	VARCHAR2(300)		NOT NULL,
	"SYNOPSIS"	VARCHAR2(2000)		NOT NULL,
	"RUNNING_TIME"	VARCHAR2(100)	DEFAULT 0	NOT NULL,
	"RATING"	VARCHAR2(30)	DEFAULT '전체관람가'	NOT NULL,
	"RELEASE_DATE"	VARCHAR2(100)		NOT NULL,
	"PRODUCER"	VARCHAR2(100)		NOT NULL,
	"MOVIE_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE"."MOVIE_TITLE" IS '영화 제목';

COMMENT ON COLUMN "MOVIE"."POSTER" IS '영화 포스터 저장 경로';

COMMENT ON COLUMN "MOVIE"."SYNOPSIS" IS '영화 시놉시스';

COMMENT ON COLUMN "MOVIE"."RUNNING_TIME" IS '영화 러닝타임';

COMMENT ON COLUMN "MOVIE"."RATING" IS '영화 관람 등급';

COMMENT ON COLUMN "MOVIE"."RELEASE_DATE" IS '영화 개봉일';

COMMENT ON COLUMN "MOVIE"."PRODUCER" IS '제작사';

COMMENT ON COLUMN "MOVIE"."MOVIE_PRICE" IS '영화 표 가격';

CREATE TABLE "MOVIE_REVIEW" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"SCORE"	NUMBER	DEFAULT 5	NOT NULL,
	"REVIEW_DATE"	VARCHAR(100)	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"MOVIE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE_REVIEW"."REVIEW_NO" IS '리뷰번호(SEQ_REVIEW_NO)';

COMMENT ON COLUMN "MOVIE_REVIEW"."SCORE" IS '영화 리뷰';

COMMENT ON COLUMN "MOVIE_REVIEW"."REVIEW_DATE" IS '리뷰 작성 시간';

COMMENT ON COLUMN "MOVIE_REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "MOVIE_REVIEW"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "MOVIE_REVIEW"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

CREATE TABLE "GENRE" (
	"GENRE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GENRE"."GENRE" IS '장르';

CREATE TABLE "MOVIE_GENRE" (
	"MOVIE_NO"	NUMBER		NOT NULL,
	"GENRE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MOVIE_GENRE"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE_GENRE"."GENRE" IS '장르';

CREATE TABLE "TICKETING_INFO" (
	"TICKET_NO"	NUMBER		NOT NULL,
	"TICKETING_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PAY_AMOUNT"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"COUPON"	VARCHAR2(100)		NOT NULL,
	"MOVIE_TIME"	DATE		NOT NULL,
	"MOVIE_THEATER"	CHAR(1)		NOT NULL,
	"MOVIE_NO"	NUMBER		NOT NULL,
	"TICKET_CANCLE"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "TICKETING_INFO"."TICKET_NO" IS '예매 번호(SEQ_TICKET_NO)';

COMMENT ON COLUMN "TICKETING_INFO"."TICKETING_TIME" IS '예매한 시간';

COMMENT ON COLUMN "TICKETING_INFO"."PAY_AMOUNT" IS '결제 금액';

COMMENT ON COLUMN "TICKETING_INFO"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "TICKETING_INFO"."COUPON" IS '쿠폰번호(SEQ_COUPON_NO)';

COMMENT ON COLUMN "TICKETING_INFO"."MOVIE_TIME" IS '상영날짜 및 시간';

COMMENT ON COLUMN "TICKETING_INFO"."MOVIE_THEATER" IS '상영관번호';

COMMENT ON COLUMN "TICKETING_INFO"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "TICKETING_INFO"."TICKET_CANCLE" IS '예메 취소 여부 ( IN "N", "Y")';

CREATE TABLE "DIRECTOR" (
	"DIRECTOR_NO"	NUMBER		NOT NULL,
	"DIRECTOR_NAME"	VARCHAR2(30)		NOT NULL,
	"DIRECTOR_PROFILE"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "DIRECTOR"."DIRECTOR_NO" IS '감독 코드 번호(SEQ_DIRECTOR_NO)';

COMMENT ON COLUMN "DIRECTOR"."DIRECTOR_NAME" IS '감독 이름';

COMMENT ON COLUMN "DIRECTOR"."DIRECTOR_PROFILE" IS '감독 프로필';

CREATE TABLE "MOVIE_DIRECTOR" (
	"MOVIE_NO"	NUMBER		NOT NULL,
	"DIRECTOR_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE_DIRECTOR"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE_DIRECTOR"."DIRECTOR_NO" IS '감독 코드 번호(SEQ_DIRECTOR_NO)';

CREATE TABLE "ACTOR" (
	"ACTOR_NO"	NUMBER		NOT NULL,
	"ACTOR_PROFILE"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "ACTOR"."ACTOR_NO" IS '배우코드번호(SEQ_ACTOR_NO)';

COMMENT ON COLUMN "ACTOR"."ACTOR_PROFILE" IS '배우 프로필';

CREATE TABLE "MOVIE_ACTOR" (
	"MOVIE_NO"	NUMBER		NOT NULL,
	"ACTOR_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE_ACTOR"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE_ACTOR"."ACTOR_NO" IS '배우코드번호(SEQ_ACTOR_NO)';

CREATE TABLE "QNA _COMMENT" (
	"QNA_COMMENT_NO"	NUMBER		NOT NULL,
	"QNA_COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"QNA_COMMENT_FL"	VARCHAR(255)	DEFAULT 'N'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"QNA_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QNA _COMMENT"."QNA_COMMENT_NO" IS '문의댓글번호(SEQ_QNACOMMENT_NO)';

COMMENT ON COLUMN "QNA _COMMENT"."QNA_COMMENT_DATE" IS '문의댓글작성일';

COMMENT ON COLUMN "QNA _COMMENT"."QNA_COMMENT_FL" IS '삭제여부(N:삭제X, Y:삭제O)';

COMMENT ON COLUMN "QNA _COMMENT"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "QNA _COMMENT"."QNA_NO" IS '문의번호(SEQ_QNA_NO)';

CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(300)		NOT NULL,
	"FAQ_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"FAQ_DELETE_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"FAQ_CATEGORY"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "FAQ"."FAQ_NO" IS '질문번호(SEQ_FAQ_NO)';

COMMENT ON COLUMN "FAQ"."FAQ_TITLE" IS '질문제목';

COMMENT ON COLUMN "FAQ"."FAQ_CONTENT" IS '질문내용';

COMMENT ON COLUMN "FAQ"."FAQ_DELETE_FL" IS '삭제여부(N:삭제X, Y:삭제O)';

COMMENT ON COLUMN "FAQ"."FAQ_CATEGORY" IS '문의 분류(P:영화관, M:영화, U:멤버쉽, B:예매/결제, H:홈페이지 A:계정)';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_TITLE"	VARCHAR2(300)		NOT NULL,
	"REPORT_CONTNENT"	VARCHAR(3000)		NOT NULL,
	"REPORT_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REPORT_DELETE_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REVIEW_NO"	NUMBER		NOT NULL,
	"REPORT_WIRTER"	NUMBER		NOT NULL,
	"REPORTED_USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호(SEQ_REPORT_NO)';

COMMENT ON COLUMN "REPORT"."REPORT_TITLE" IS '신고제목';

COMMENT ON COLUMN "REPORT"."REPORT_CONTNENT" IS '신고내용';

COMMENT ON COLUMN "REPORT"."REPORT_ENROLL_DATE" IS '신고등록일';

COMMENT ON COLUMN "REPORT"."REPORT_FL" IS '처리여부(N: 처리X, Y: 처리O)';

COMMENT ON COLUMN "REPORT"."REPORT_DELETE_FL" IS '삭제여부(N:삭제X, Y:삭제O)';

COMMENT ON COLUMN "REPORT"."REVIEW_NO" IS '리뷰번호(SEQ_REVIEW_NO)';

COMMENT ON COLUMN "REPORT"."REPORT_WIRTER" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "REPORT"."REPORTED_USER_NO" IS '회원 번호(SEQ_USER_NO)';

CREATE TABLE "USER_COUPON" (
	"USER_NO"	NUMBER		NOT NULL,
	"COUPON"	VARCHAR2(100)		NOT NULL,
	"USE_FL"	VARCHAR2(3)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "USER_COUPON"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "USER_COUPON"."COUPON" IS '쿠폰번호(SEQ_COUPON_NO)';

COMMENT ON COLUMN "USER_COUPON"."USE_FL" IS '쿠폰 사용 여부 N, Y';

CREATE TABLE "COUPON" (
	"COUPON"	VARCHAR2(100)		NOT NULL,
	"COUPON_PRICE"	NUMBER	DEFAULT 10000	NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON" IS '쿠폰번호(SEQ_COUPON_NO)';

COMMENT ON COLUMN "COUPON"."COUPON_PRICE" IS '쿠폰 가격';

CREATE TABLE "MEMBERSHIP" (
	"USER_RATING"	NUMBER		NOT NULL,
	"UPGRADE"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "MEMBERSHIP"."USER_RATING" IS '멤버십 등급';

COMMENT ON COLUMN "MEMBERSHIP"."UPGRADE" IS '등급 상승 기준';

CREATE TABLE "USER_MEMBERSHIP" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_RATING"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "USER_MEMBERSHIP"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "USER_MEMBERSHIP"."USER_RATING" IS '멤버십 등급';

CREATE TABLE "MOVIE_IMG" (
	"MOVIE_IMG"	NUMBER		NOT NULL,
	"MOVIE_NO"	NUMBER		NOT NULL,
	"MOVIE_IMG_PATH"	VARCHAR2(2000)		NULL
);

COMMENT ON COLUMN "MOVIE_IMG"."MOVIE_IMG" IS '영화 이미지 번호(SEQ_MOVIE_IMG_NO)';

COMMENT ON COLUMN "MOVIE_IMG"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE_IMG"."MOVIE_IMG_PATH" IS '영화 이미지 경로';

CREATE TABLE "MOVIE_SEAT" (
	"MOVIE_NO"	NUMBER		NOT NULL,
	"MOVIE_TIME"	DATE		NOT NULL,
	"MOVIE_THEATER"	CHAR(1)		NOT NULL,
	"SEAT_NO"	VARCHAR2(10)		NOT NULL,
	"TICKET_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MOVIE_SEAT"."MOVIE_NO" IS '영화번호(SEQ_MOVIE_NO)';

COMMENT ON COLUMN "MOVIE_SEAT"."MOVIE_TIME" IS '상영날짜 및 시간';

COMMENT ON COLUMN "MOVIE_SEAT"."MOVIE_THEATER" IS '상영관번호';

COMMENT ON COLUMN "MOVIE_SEAT"."SEAT_NO" IS '좌석번호';

COMMENT ON COLUMN "MOVIE_SEAT"."TICKET_NO" IS '예매 번호(SEQ_TICKET_NO)';

ALTER TABLE "USER_INFO" ADD CONSTRAINT "PK_USER_INFO" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "SALES" ADD CONSTRAINT "PK_SALES" PRIMARY KEY (
	"YEAR_QUATER"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_NO"
);

ALTER TABLE "MOVIE_SCHEDULE" ADD CONSTRAINT "PK_MOVIE_SCHEDULE" PRIMARY KEY (
	"MOVIE_TIME",
	"MOVIE_THEATER",
	"MOVIE_NO"
);

ALTER TABLE "SEAT" ADD CONSTRAINT "PK_SEAT" PRIMARY KEY (
	"SEAT_NO"
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_REVIEW" ADD CONSTRAINT "PK_MOVIE_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE"
);

ALTER TABLE "MOVIE_GENRE" ADD CONSTRAINT "PK_MOVIE_GENRE" PRIMARY KEY (
	"MOVIE_NO",
	"GENRE"
);

ALTER TABLE "TICKETING_INFO" ADD CONSTRAINT "PK_TICKETING_INFO" PRIMARY KEY (
	"TICKET_NO"
);

ALTER TABLE "DIRECTOR" ADD CONSTRAINT "PK_DIRECTOR" PRIMARY KEY (
	"DIRECTOR_NO"
);

ALTER TABLE "MOVIE_DIRECTOR" ADD CONSTRAINT "PK_MOVIE_DIRECTOR" PRIMARY KEY (
	"MOVIE_NO",
	"DIRECTOR_NO"
);

ALTER TABLE "ACTOR" ADD CONSTRAINT "PK_ACTOR" PRIMARY KEY (
	"ACTOR_NO"
);

ALTER TABLE "MOVIE_ACTOR" ADD CONSTRAINT "PK_MOVIE_ACTOR" PRIMARY KEY (
	"MOVIE_NO",
	"ACTOR_NO"
);

ALTER TABLE "QNA _COMMENT" ADD CONSTRAINT "PK_QNA _COMMENT" PRIMARY KEY (
	"QNA_COMMENT_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "PK_USER_COUPON" PRIMARY KEY (
	"USER_NO",
	"COUPON"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON"
);

ALTER TABLE "MEMBERSHIP" ADD CONSTRAINT "PK_MEMBERSHIP" PRIMARY KEY (
	"USER_RATING"
);

ALTER TABLE "USER_MEMBERSHIP" ADD CONSTRAINT "PK_USER_MEMBERSHIP" PRIMARY KEY (
	"USER_NO",
	"USER_RATING"
);

ALTER TABLE "MOVIE_IMG" ADD CONSTRAINT "PK_MOVIE_IMG" PRIMARY KEY (
	"MOVIE_IMG",
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_SEAT" ADD CONSTRAINT "PK_MOVIE_SEAT" PRIMARY KEY (
	"MOVIE_NO",
	"MOVIE_TIME",
	"MOVIE_THEATER",
	"SEAT_NO",
	"TICKET_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "FK_USER_INFO_TO_QNA_1" FOREIGN KEY (
	"USER_NO2"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "MOVIE_SCHEDULE" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_SCHEDULE_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_REVIEW" ADD CONSTRAINT "FK_USER_INFO_TO_MOVIE_REVIEW_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "MOVIE_REVIEW" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_REVIEW_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_GENRE" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_GENRE_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_GENRE" ADD CONSTRAINT "FK_GENRE_TO_MOVIE_GENRE_1" FOREIGN KEY (
	"GENRE"
)
REFERENCES "GENRE" (
	"GENRE"
);

ALTER TABLE "TICKETING_INFO" ADD CONSTRAINT "FK_USER_COUPON_TO_TICKETING_INFO_1" FOREIGN KEY (
	"USER_NO", "COUPON"
)
REFERENCES "USER_COUPON" (
	"USER_NO","COUPON"
);


ALTER TABLE "TICKETING_INFO" ADD CONSTRAINT "FK_MOVIE_SCHEDULE_TO_TICKETING_INFO" FOREIGN KEY (
	"MOVIE_TIME", "MOVIE_THEATER", "MOVIE_NO"
)
REFERENCES "MOVIE_SCHEDULE" (
	"MOVIE_TIME", "MOVIE_THEATER", "MOVIE_NO"
);



ALTER TABLE "MOVIE_DIRECTOR" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_DIRECTOR_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_DIRECTOR" ADD CONSTRAINT "FK_DIRECTOR_TO_MOVIE_DIRECTOR_1" FOREIGN KEY (
	"DIRECTOR_NO"
)
REFERENCES "DIRECTOR" (
	"DIRECTOR_NO"
);

ALTER TABLE "MOVIE_ACTOR" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_ACTOR_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_ACTOR" ADD CONSTRAINT "FK_ACTOR_TO_MOVIE_ACTOR_1" FOREIGN KEY (
	"ACTOR_NO"
)
REFERENCES "ACTOR" (
	"ACTOR_NO"
);

ALTER TABLE "QNA _COMMENT" ADD CONSTRAINT "FK_USER_INFO_TO_QNA _COMMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "QNA _COMMENT" ADD CONSTRAINT "FK_QNA_TO_QNA _COMMENT_1" FOREIGN KEY (
	"QNA_NO"
)
REFERENCES "QNA" (
	"QNA_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MOVIE_REVIEW_TO_REPORT_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "MOVIE_REVIEW" (
	"REVIEW_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_USER_INFO_TO_REPORT_1" FOREIGN KEY (
	"REPORT_WIRTER"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_USER_INFO_TO_REPORT_2" FOREIGN KEY (
	"REPORTED_USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "FK_USER_INFO_TO_USER_COUPON_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "FK_COUPON_TO_USER_COUPON_1" FOREIGN KEY (
	"COUPON"
)
REFERENCES "COUPON" (
	"COUPON"
);

ALTER TABLE "USER_MEMBERSHIP" ADD CONSTRAINT "FK_USER_INFO_TO_USER_MEMBERSHIP_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "USER_MEMBERSHIP" ADD CONSTRAINT "FK_MEMBERSHIP_TO_USER_MEMBERSHIP_1" FOREIGN KEY (
	"USER_RATING"
)
REFERENCES "MEMBERSHIP" (
	"USER_RATING"
);

ALTER TABLE "MOVIE_IMG" ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_IMG_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
);

ALTER TABLE "MOVIE_SEAT" ADD CONSTRAINT "FK_MOVIE_SCHEDULE_TO_MOVIE_SEAT" FOREIGN KEY (
	"MOVIE_NO", "MOVIE_TIME", "MOVIE_THEATER"
)
REFERENCES "MOVIE_SCHEDULE" (
	"MOVIE_NO", "MOVIE_TIME", "MOVIE_THEATER" 
);


ALTER TABLE "MOVIE_SEAT" ADD CONSTRAINT "FK_SEAT_TO_MOVIE_SEAT_1" FOREIGN KEY (
	"SEAT_NO"
)
REFERENCES "SEAT" (
	"SEAT_NO"
);

ALTER TABLE "MOVIE_SEAT" ADD CONSTRAINT "FK_TICKETING_INFO_TO_MOVIE_SEAT_1" FOREIGN KEY (
	"TICKET_NO"
)
REFERENCES "TICKETING_INFO" (
	"TICKET_NO"
);

