
CREATE SEQUENCE SEQ_USER_NO NOCACHE; --회원 번호(SEQ_USER_NO)

CREATE SEQUENCE SEQ_COUPON_NO NOCACHE; -- 쿠폰번호(SEQ_COUPON_NO)

CREATE SEQUENCE SEQ_QNA_NO NOCACHE; -- 문의번호(SEQ_QNA_NO)

CREATE SEQUENCE SEQ_QNACOMMENT_NO NOCACHE; -- 문의댓글번호(SEQ_QNACOMMENT_NO)

CREATE SEQUENCE SEQ_FAQ_NO NOCACHE; -- 질문번호(SEQ_FAQ_NO)

CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE; -- 공지사항번호(SEQ_NOTICE_NO)

CREATE SEQUENCE SEQ_TICKET_NO NOCACHE; -- 예매 번호(SEQ_TICKET_NO)

CREATE SEQUENCE SEQ_MOVIE_NO NOCACHE; -- 영화번호(SEQ_MOVIE_NO)

CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE; -- 리뷰번호(SEQ_REVIEW_NO)

CREATE SEQUENCE SEQ_MOVIE_IMG_NO NOCACHE; -- 영화 이미지 번호(SEQ_MOVIE_IMG_NO)

CREATE SEQUENCE SEQ_DIRECTOR_NO NOCACHE; -- 감독 코드 번호(SEQ_DIRECTOR_NO)

CREATE SEQUENCE SEQ_ACTOR_NO NOCACHE; -- 배우코드번호(SEQ_ACTOR_NO)

CREATE SEQUENCE SEQ_REPORT_NO NOCACHE; -- 신고번호(SEQ_REPORT_NO)










