
-- MOVIE TABLE

	-- 제작자 컬럼 삭제
ALTER TABLE "beansGarden".MOVIE DROP CONSTRAINT SYS_C0010910;
ALTER TABLE "beansGarden".MOVIE DROP COLUMN PRODUCER;

	-- 메인 포스터 컬럼 삭제 
ALTER TABLE "beansGarden".MOVIE DROP COLUMN MAIN_POSTER;
