-- 근태님 userTable birth,gender -> 주민번호로 변경
ALTER TABLE "beansGarden".USER_INFO DROP CONSTRAINT SYS_C0010878;
ALTER TABLE "beansGarden".USER_INFO DROP COLUMN USER_BIRTH;
ALTER TABLE "beansGarden".USER_INFO DROP CONSTRAINT SYS_C0010879;
ALTER TABLE "beansGarden".USER_INFO DROP COLUMN USER_GENDER;
ALTER TABLE "beansGarden".USER_INFO ADD USER_REGINUM CHAR(8) NOT NULL;
COMMENT ON COLUMN "beansGarden".USER_INFO.USER_REGINUM IS '회원 주민등록번호(YYMMDD-G*******)';

-- 쿠폰 테이블 -> PRIMARY KEY : VARCHAR2(100) -> NUMBER로 변경
-- 제약 설정으로 인한 ALTER 불편 -> 아직 샘플 데이터가 없는 관계로 테이블을 다시 지우기 새로 생성
CREATE TABLE "COUPON" (
	"COUPON"	NUMBER		NOT NULL,
	"COUPON_PRICE"	NUMBER	DEFAULT 10000	NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON" IS '쿠폰번호(SEQ_COUPON_NO)';

COMMENT ON COLUMN "COUPON"."COUPON_PRICE" IS '쿠폰 가격';

CREATE TABLE "USER_COUPON" (
	"USER_NO"	NUMBER		NOT NULL,
	"COUPON"	NUMBER		NOT NULL,
	"USE_FL"	VARCHAR2(3)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "USER_COUPON"."USER_NO" IS '회원 번호(SEQ_USER_NO)';

COMMENT ON COLUMN "USER_COUPON"."COUPON" IS '쿠폰번호(SEQ_COUPON_NO)';

COMMENT ON COLUMN "USER_COUPON"."USE_FL" IS '쿠폰 사용 여부 N, Y';

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "PK_USER_COUPON" PRIMARY KEY (
	"USER_NO",
	"COUPON"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "FK_USER_INFO_TO_USER_COUPON_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER_INFO" (
	"USER_NO"
);

ALTER TABLE "USER_COUPON" ADD CONSTRAINT "FK_COUPON_TO_USER_COUPON_1" FOREIGN KEY (
	"COUPON"
)
REFERENCES "COUPON" (
	"COUPON"
);


-- 티켓 정보에 쿠폰 번호 NULL로 설정 및 형태 NUMBER로 변경
ALTER TABLE "beansGarden".TICKETING_INFO MODIFY COUPON NUMBER NULL;


