ALTER TABLE "beansGarden".MOVIE_IMG ADD MOVIE_IMG_ROLE VARCHAR2(100) NOT NULL;
ALTER TABLE "beansGarden".MOVIE_IMG MODIFY MOVIE_IMG_PATH VARCHAR2(2000) NOT NULL;
COMMENT ON COLUMN "beansGarden".MOVIE_IMG.MOVIE_IMG_ROLE IS 'IN 메인슬라이드, 영화 슬라이드, 광고 , 스틸컷';
ALTER TABLE "beansGarden".MOVIE_IMG RENAME COLUMN MOVIE_IMG TO MOVIE_IMG_NO;
