SELECT SEQ_USER_NO.NEXTVAL FROM DUAL;
SELECT SEQ_USER_NO.CURRVAL FROM DUAL;

INSERT INTO "USER_INFO"
VALUES(SEQ_USER_NO.NEXTVAL, 'TEST2ID', 'TEST2PW', 'TEST2NICK', '01099999999', 'TES2T@TEST2.com'
		, SYSDATE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, '20220222', 'F');
	
INSERT INTO "USER_INFO"
VALUES(SEQ_USER_NO.NEXTVAL
, #{userId}
, #{userPw}
, #{userNickname}
, #{userTel}
, #{userEmail}
, SYSDATE
, DEFAULT
, DEFAULT
, DEFAULT
, DEFAULT
, #{userBirht}
, #{userGender});

COMMIT;
ROLLBACK;

SELECT * FROM USER_INFO ORDER BY 1;
SELECT * FROM TICKETING_INFO ORDER BY 1;
SELECT * FROM SEAT_CHECK;

SELECT RTRIM(TO_CHAR(TICKETING_TIME, 'DAY', 'NLS_DATE_LANGUAGE = ENGLISH')) AS TICKETING_DAY, COALESCE(SUM(PAY_AMOUNT), 0) AS TOTAL_SALES, TRUNC(TICKETING_TIME) AS TICKETING_DATE
FROM TICKETING_INFO
WHERE TICKETING_TIME >= TRUNC(SYSDATE, 'IW') - 7
AND TICKETING_TIME < TRUNC(SYSDATE, 'IW')
GROUP BY TO_CHAR(TICKETING_TIME, 'DAY', 'NLS_DATE_LANGUAGE = ENGLISH'), TRUNC(TICKETING_TIME)
ORDER BY TRUNC(TICKETING_TIME);

SELECT
  TO_CHAR(TICKETING_TIME, 'YYYY') AS YEAR,
  TO_CHAR(TICKETING_TIME, 'Q') AS QUARTER,
  SUM(PAY_AMOUNT) AS TOTAL_AMOUNT
FROM
  TICKETING_INFO
WHERE
  TO_CHAR(TICKETING_TIME, 'YYYY') = '2023'
GROUP BY
  TO_CHAR(TICKETING_TIME, 'YYYY'),
  TO_CHAR(TICKETING_TIME, 'Q')
ORDER BY
  TO_CHAR(TICKETING_TIME, 'YYYY'),
  TO_CHAR(TICKETING_TIME, 'Q');
 
 
SELECT "YEAR_AND_MONTH", 
       CASE WHEN SUBSTR("YEAR_AND_MONTH", 1, 4) = '2023' THEN "THIS_YEAR"
            WHEN SUBSTR("YEAR_AND_MONTH", 1, 4) = '2022' THEN "LAST_YEAR"
            ELSE NULL
       END AS "MONTHLY_SALES_BY_YEAR"
FROM (
  SELECT TO_CHAR(TICKETING_TIME, 'YYYY-MM') AS "YEAR_AND_MONTH",
         SUM(CASE WHEN EXTRACT(YEAR FROM TICKETING_TIME) = 2023 THEN PAY_AMOUNT ELSE 0 END) AS "THIS_YEAR",
         SUM(CASE WHEN EXTRACT(YEAR FROM TICKETING_TIME) = 2022 THEN PAY_AMOUNT ELSE 0 END) AS "LAST_YEAR"
  FROM TICKETING_INFO
  GROUP BY TO_CHAR(TICKETING_TIME, 'YYYY-MM'), EXTRACT(YEAR FROM TICKETING_TIME)
)
WHERE SUBSTR("YEAR_AND_MONTH", 1, 4) IN ('2023', '2022')
ORDER BY SUBSTR("YEAR_AND_MONTH", 6, 2) ASC, SUBSTR("YEAR_AND_MONTH", 1, 4);


SELECT M.MOVIE_TITLE, COUNT(*) AS TICKET_COUNT
FROM TICKETING_INFO T
JOIN MOVIE M ON T.MOVIE_NO = M.MOVIE_NO
WHERE T.TICKETING_TIME >= ADD_MONTHS(TRUNC(SYSDATE), -3)
AND TICKET_FL = 'Y'
GROUP BY M.MOVIE_TITLE;

SELECT M.MOVIE_TITLE, COUNT(*) AS TICKET_COUNT
FROM TICKETING_INFO T
JOIN MOVIE M ON T.MOVIE_NO = M.MOVIE_NO
WHERE TICKETING_TIME >= TO_DATE(2023-07-6) AND TICKETING_TIME <  TO_DATE('2023-07-26')
AND TICKET_FL = 'Y'
GROUP BY M.MOVIE_TITLE;

   
SELECT COUNT(*) FROM TICKETING_INFO WHERE TICKET_ID LIKE '953624-0626%';

UPDATE TICKETING_INFO SET TICKET_ID = '54360-0626-031112' WHERE TICKET_NO = '102';

UPDATE TICKETING_INFO SET REASON_CANCELLATION_PAYMENT = '결제 금액 오류' WHERE TICKET_ID = '953624-0626-03001';

UPDATE TICKETING_INFO SET TICKEY_IMP_UID = '힝' WHERE TICKET_ID = '953624-0626-03001';

UPDATE TICKETING_INFO SET TICKET_FL = 'Y' WHERE TICKET_ID = '953624-0626-03001';

UPDATE TICKETING_INFO SET PAY_AMOUNT = 12000 * #{seatListSize}
		WHERE TICKET_NO = #{ticketNo};

SELECT USER_NO, USER_ID, USER_PW, USER_NICKNAME, USER_TEL, USER_EMAIL, 
		TO_CHAR(USER_ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"')
		USER_ENROLL_DT, USER_AMOUNT, USER_ROLE, USER_RATING, USER_CLOSE, USER_BIRTH, USER_GENDER
FROM "USER_INFO"
WHERE USER_CLOSE = 'N'
AND USER_ID = 'DGCadmin';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_EMAIL  = '123123@123123.com'
AND USER_CLOSE = 'N';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_ID  = '123123'
AND USER_CLOSE = 'N';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_NICKNAME  = '123123'
AND USER_CLOSE = 'N';

SELECT USER_ID 
FROM "USER_INFO"
WHERE USER_BIRTH  = '20220202'
AND USER_TEL  = '01012341234'
AND USER_CLOSE = 'N';

UPDATE "USER_INFO" SET
USER_PW  = '1231'
WHERE USER_ID = '123123';


















