SELECT SEQ_USER_NO.NEXTVAL FROM DUAL;
SELECT SEQ_USER_NO.CURRVAL FROM DUAL;

INSERT INTO "USER_INFO"
VALUES(SEQ_USER_NO.NEXTVAL, 'TEST1', 'TEST1', 'TEST1', '01099999999', 'TEST@TEST.com'
		, SYSDATE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, '000102-3');

COMMIT;
ROLLBACK;

SELECT * FROM USER_INFO;

SELECT USER_NO , USER_ID , USER, MEMBER_URL, MEMBER_PW,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"')
ENROLL_DATE, AUTHORITY
FROM "USER_INFO"
WHERE MEMBER_DEL_FL = 'N'
AND MEMBER_EMAIL = #{memberEmail};

SELECT USER_NO, USER_ID, USER_PW, USER_NICKNAME, USER_TEL, USER_EMAIL, 
		TO_CHAR(USER_ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"')
		USER_ENROLL_DT, USER_AMOUNT, USER_ROLE, USER_RATING, USER_CLOSE, USER_REGINUM

FROM "USER_INFO"
WHERE USER_CLOSE = 'N'
AND USER_ID = '123123';

AND USER_ID = #{userId};

