SELECT SEQ_USER_NO.NEXTVAL FROM DUAL;
SELECT SEQ_USER_NO.CURRVAL FROM DUAL;

INSERT INTO "USER_INFO"
VALUES(SEQ_USER_NO.NEXTVAL, 'TEST2ID', 'TEST2PW', 'TEST2NICK', '01099999999', 'TES2T@TEST2.com'
		, SYSDATE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, '20220222', 'F');
	
INSERT INTO "USER_INFO"
VALUES(SEQ_USER_NO.NEXTVAL
, #{userId}
, #{userPw}
, #{userNickname}
, #{userTel}
, #{userEmail}
, SYSDATE
, DEFAULT
, DEFAULT
, DEFAULT
, DEFAULT
, #{userBirht}
, #{userGender});

COMMIT;
ROLLBACK;

SELECT * FROM USER_INFO;

SELECT USER_NO, USER_ID, USER_PW, USER_NICKNAME, USER_TEL, USER_EMAIL, 
		TO_CHAR(USER_ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"')
		USER_ENROLL_DT, USER_AMOUNT, USER_ROLE, USER_RATING, USER_CLOSE, USER_BIRTH, USER_GENDER
FROM "USER_INFO"
WHERE USER_CLOSE = 'N'
AND USER_ID = '123123';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_EMAIL  = '123123@123123.com'
AND USER_CLOSE = 'N';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_ID  = '123123'
AND USER_CLOSE = 'N';

SELECT COUNT(*)
FROM "USER_INFO"
WHERE USER_NICKNAME  = '123123'
AND USER_CLOSE = 'N';

SELECT USER_ID 
FROM "USER_INFO"
WHERE USER_BIRTH  = '20220202'
AND USER_TEL  = '01012341234'
AND USER_CLOSE = 'N';




















